name: "Digital Signage Server"
description: "Manage screens and playlists for Raspberry Pi digital signage clients."
version: "1.0.6"
slug: "digital_signage_server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - data:rw
ports:
  9999/tcp: 9999
panel_icon: "mdi:monitor-dashboard"
panel_title: "Digital Signage"
ingress: true
ingress_port: 8099
ingress_stream: true
apparmor: true
host_network: true
options: {}
schema: {}
